INSERT INTO keywords (name, created_at) VALUES
('토익', CURRENT_TIMESTAMP),
('일본어', CURRENT_TIMESTAMP),
('취업', CURRENT_TIMESTAMP),
('코딩테스트', CURRENT_TIMESTAMP),
('알고리즘', CURRENT_TIMESTAMP),
('Spring', CURRENT_TIMESTAMP),
('React', CURRENT_TIMESTAMP),
('SQL', CURRENT_TIMESTAMP),
('영어회화', CURRENT_TIMESTAMP),
('자격증', CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE name = VALUES(name);
